# ?????? ?? ??
spring:
  application:
    name: NPKI

  # ?? ??? ?? ??
  servlet:
    multipart:
      max-file-size: 10MB  # ?? ?? ??
      max-request-size: 30MB  # ?? ?? ??

  jpa:
    open-in-view: false  # "Open EntityManager in View" ??
    show-sql: true  # JPA SQL ?? ??
    hibernate:
      ddl-auto: update  # Hibernate DDL ?? ?? ?? (?? ????? ??)
      format_sql: true  # Hibernate SQL ?? ?? (???? ??)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Hibernate ??? ??? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Hibernate가 사용할 SQL 직접 지정

  mvc:
    hiddenmethod:
      filter:
        enabled: true  # Hidden HTTP Methods ?? ?? (HTML Form?? PUT, DELETE ?? ???? ??)
    static-path-pattern: "/static/**"  # ?? ?? ?? ??

  thymeleaf:
    cache: false  # Thymeleaf ??? ?? ???? (?? ? ?? ??? ??? ??)

  h2:
    console:
      enabled: true  # H2 ?? ??? (?? ?? ????? ????)

  messages:
    basename: classpath:messages  # ??? ??? ?? ??

  profiles:
    include: secret  # secret ????? ??? ???? ??? ?? ??
    active: dev  # ?? ????? DEBUG ?? ???

  # ?????? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate SQL ?? ??
logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.servlet.DispatcherServlet: DEBUG
        security: DEBUG
        beans: DEBUG
        jdbc.core.JdbcTemplate: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
      apache:
        coyote.http11: WARN
        tomcat.util.net: WARN

# Actuator ??
management:
  metrics:
    profiler:
      enabled: true  # ??? ????? ???
  endpoints:
    web:
      exposure:
        include: "*"  # Actuator ????? ?? ??
      base-path: "/actuator/profiler"  # Actuator ????? ?? ?? ??

# Tomcat ??? ????? ??
server:
  tomcat:
    use-relative-redirects: true

  # Whitelabel ?? ??? ????
  error:
    whitelabel:
      enabled: false

  servlet:
    session:
      cookie:
        http-only: false  # HTTP-Only ?? ??